module.exports={
    elements:{
        analyzeHeader:'.ui-page-title h1',
        legendItem:'.legend-item',
        tileHeader:'.ui-graph .ui-card-header',
        xAxisLabel:'.ui-graph .x.axis-label',
        yAxisLabel:'.ui-graph .y.axis-label',
        articleListContainer:'.analyze-content-articles-col',
        articleListProfileSelector:'.article-list-profile-selector',
        articleListSummaryTab:'.article-tabs .article-tabs_tabs div.article-tabs_tab:nth-of-type(1)',
        articleListStatisticsTab:'.article-tabs .article-tabs_tabs div.article-tabs_tab:nth-of-type(1)',
        articleListBradSentimentTab:'.article-tabs .article-tabs_tabs div.article-tabs_tab:nth-of-type(1)',
        closeExtendedArticles:'.article-extended-close',
        selectFirst100:'.article-list-card .ui-three-dots ul li:nth-of-type(4)',
        deselectAll:'.article-list-card .ui-three-dots ul li:nth-of-type(5)',
        threeDotsArticleList:'.article-list-card .ui-three-dots',
        optionsDropdownArticleList:'.article-list-card .ui-three-dots ul',
        articleListHeader:'.article-list-card .ui-card-header h6',
        searchAndFilterTitle:'.search-and-filter .header .title',
        analyzeDropdown:'.ui-page-title-nav-section a',
        neoMessagingPane:'.analyze-content-messaging-col',
        soundbytePerformancePane:'.analyze-content-messaging-graph-col',
        searchFilterName:'input[placeholder="Name this search"]',
        confirmationPopUp:'.modal-dialog .modal-content',

    },
}