module.exports={
    elements:{
        reportsHeader:'.ui-page-title h1',
        newReportDialog:'.report-new-panel .modal-panel-pane',
        reportName:'input[placeholder="Untitled Report"]',
        newReportProfileSelector:'.profile-menu a',
        profileSearch:'.profile-menu ul input',
        dateSelector:'.ui-calendar-range a',
        extendedReportPage:'.report-content',
        titlePage:'ul div[data-page="0"]',
        reportContentTitle:'.report-content .report-title-last-text',
        reportContentDateRange:'.report-content .date-range',
        option_charts:".nav-charts",
        option_articles:".nav-articles",
        option_tiles:".nav-tiles",
        option_texts:".nav-texts",
        option_images:".nav-images",
        reportContentTiles:'.report-content .grid-item',
        reportSizeDropdown:'.report-content div.report-tool-toolbar-resize',
        reportWidgetDestory:'.report-content .grid-item .report-tool-toolbar-destroy',
        editReportPopup:'.report-edit-form',
        informationPopup:'.modal-content',
        reportTitle:'.report-title',
        reportSearchBox:'input[placeholder="Search"]',
        reportPrivacy:'.report-privacy',
        previewClose:'.modal-panel-pane a.close,.ui-close',
    },
}